version: '2'
services:
  hadoop-master:
    hostname: hadoop-master
    image: 'prestodev/hdp2.5-hive:13'
    ports:
      - '1080:1080'
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'

  psql1:
    hostname: psql1
    image: 'postgres'
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: blah
      POSTGRES_PASSWORD: blah

  psql2:
    hostname: psql2
    image: 'postgres'
    ports:
      - '15433:5432'
    environment:
      POSTGRES_USER: blah
      POSTGRES_PASSWORD: blah

  cassandra:
    hostname: cassandra
    image: 'cassandra:2.1.15'
    ports:
      - '9042:9042'
      - '9160:9160'

  kafka:
    hostname: kafka
    image: spotify/kafka
    ports:
      - 9092:9092
      - 2181:2181
    command: bash -c "sed -i 's/#delete.topic.enable=true/delete.topic.enable=true/' /opt/kafka_2.11-0.10.1.0/config/server.properties; exec supervisord -n"


  ssh:
    hostname: ssh
    build: 'ssh'
    ports:
      - '2222:22'

  presto-master:
    hostname: presto-master
    build: 'presto-server'
    ports: 
      - '8080:8080'
    depends_on:
      - 'cassandra'
      - 'hadoop-master'
      - 'psql1'
      - 'psql2'
      - 'kafka'

  presto-cli:
    build: 'presto-cli'
    depends_on:
      - 'presto-master'

  runner:
    image: 'prestodev/centos6-oj8:13'
    ports:
      - '5005:5005'
    volumes:
      - '..:/workspace'
    depends_on:
      - 'presto-master'

